{% set name = "luarocks" %}
{% set version = "3.6.0" %}
{% set sha256 = "f04f89ad9d4d1a4e84531986d45ecff9d2a46395f8732e29f203d915eb25310b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://luarocks.github.io/luarocks/releases/luarocks-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [not linux or not x86] 
  detect_binary_files_with_prefix: True

requirements:
  build:
    - lua
    - unzip
  run:
    - lua
    - unzip

test:
  commands:
    - luarocks --version

about:
  home: https://luarocks.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: 'LuaRocks is the package manager for Lua modulesLuaRocks is the package manager for Lua module'

  description: |
      LuaRocks is the package manager for Lua modules.
      It allows you to create and install Lua modules as self-contained
      packages called rocks. You can download and install LuaRocks on Unix and
      Windows.
  doc_url: https://github.com/luarocks/luarocks/wiki/Documentation
  dev_url: https://github.com/luarocks/luarocks/

extra:
  recipe-maintainers:
    - jerowe
