travis:
  secure:
    BINSTAR_TOKEN: jNc/4rZtkjPAQbXB9mfhiNB5VbE1EWFfFkCBLA0CTq+qLs87tzpFqn17kVB9RUg3IhtLkyohxBkyKnxLKPkcr9Z5lBqOm9ztkXdx1Kr1aBzAY1brkyXfNvT7ZmFrgxlzKcpGgYe58UtkoJ0ZpMYlvnRFnA4dgvplkDNZk/QA/U1rGJqE46V9x96mtQHG/T8ha48rzyxLpWd3LfTmAdWnddY195kWVXVdDw/Fd9pptUNgb8/azslw5Mi4EXHFugJKhx6TcaXR1lO795BikPqEp65KrWbEtXA0JbK0i52cM6sBWWmCzIbJRagQ47Nc37zl/Ma+zljbvw5jmxiunm9eu49StyE+zVAY9VPO0eH3CLdWA9M1JDqpTpsZvcokUuKS5oA9d6+LteShhEJk57Fs/tleksZwYyaLfpLtjlnduwAiPuMXAq6zZxVezoEcBw4oZiwaEKYThWEVr7uhtLVyke71SUpTDqMr7Ey0aSYobhJTgF1pSc0s17nYmHb5Tc2dWKLmctaJAnDvqzr0vRBnUopVAglrZpYvXZTiY106JdZRWWefFbF8H4IxjJUV51V95Qtd2RyULSRaRAOwPErIIgGxPDsSYidQMtUB2mw6Z+3T5Q1Otw0zgeqT1RCduJ/DERNwpmq8Pn/BfLo8UvxzLwyiz0RlQO4EamjQtEcW8h8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
