travis:
  secure:
    BINSTAR_TOKEN: VahYFwxd4pK5TZDPO4YRa63hudxqoSXFSN5ng/7aUVv0hFjOOJU/7aZemflCYKt1BiTEjpz22SruMuwp5iDza9fOTVMcAvlfNF1ncTPqEG6fYBHh4139Sv9gToq4FvFN3HxPesRdPlCgYYRCrRhSlkNA38Zr8jnR11JPnllhzJP8zinrEFMxy+QGe4UeZyjBnJKN7PAj8sCO30BLp87dHuoRQcubiNbczsU38ndQDaq1pWDnEbnjk0X7mYsmb1EmyqhJmPysrC4phBdVfkr1dxH8jQ+pHitvJWkmn1yf4QUjh1D6itmzKsZT9GOFJ3SzcDera/NAa3iTmdn3AtPhtxS9R0E94pXiMWYNGVyPfKH4372FyveU8X/+YjLlGAn2NdgewJH4+KQasXJ/x+cNoj/6GgqZ/+h7qZ4kbLF/34FhnOEx7YFwjeVqx0OwnPvlFq89epzWGAKlTKrSemDDZ9PY2K2Y01LzSfcLR0QbQ48GlrRKQN9Q7tF+yFeNDPPgyyabRwjCvcf6nqrDhDZhe8j9UpenwKtjQ35Sbp2+i/sxl7ZP1Tt3vll6WaBk6c0zliOP/kDDouW3oBbp482JqtZ6Rnpu1wvkYFlW1Q4Ok1yfpeMuQKaao+OpWhkoK9hAQhhRDoPNO/38Aeb2lCQczpsQXmF+0apLIIzd69YQmhU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
